apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel

commonLabels:
  app.kubernetes.io/part-of: k8s-sentinel

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-metrics.yaml
  - webhook-config.yaml
  - cert-manager.yaml
  - poddisruptionbudget.yaml
